version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      TEST_DB_HOST: postgres
      TEST_DB_PORT: 5432
      TEST_DB_NAME: test_db
      TEST_DB_USER: test_user
      TEST_DB_PASSWORD: test_password
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    depends_on:
      - postgres
